excluded:
  - .build/
  - build/

line_length: 140
file_length: 1500
function_parameter_count: 7
opt_in_rules:
  - empty_count
  - empty_string
disabled_rules:
  - cyclomatic_complexity
  - large_tuple
  - force_cast
  - force_try
  - function_body_length
  - todo
  - type_body_length
  - identifier_name
  - trailing_whitespace
  - unused_optional_binding
